# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 06:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(editable=False)),
                ('modified_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('group_id', models.CharField(blank=True, max_length=20, null=True)),
                ('classification_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('classification_probabilities', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('text', models.TextField()),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('classifier.basemodel',),
        ),
        migrations.CreateModel(
            name='ClassifiedExcerpt',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('classification_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('classification_probabilities', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('classified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='classifier.ClassifiedDocument')),
            ],
            bases=('classifier.basemodel',),
        ),
        migrations.CreateModel(
            name='ClassifierModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(editable=False, max_length=20, unique=True)),
                ('_data', models.TextField(db_column='data')),
                ('accuracy', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('test_file_path', models.CharField(max_length=250, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('classifier.basemodel',),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('text', models.TextField()),
                ('classification_label', models.CharField(max_length=50)),
                ('useful', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('used_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ClassifierModel')),
            ],
            bases=('classifier.basemodel',),
        ),
        migrations.AddField(
            model_name='classifieddocument',
            name='classifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ClassifierModel'),
        ),
    ]
