# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 02:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('group_id', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('classification_probabilities', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('text', models.TextField()),
                ('details', models.TextField()),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ClassifierModel')),
            ],
            bases=('classifier.basemodel',),
        ),
        migrations.CreateModel(
            name='ClassifiedExcerpt',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('classification', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0)),
                ('classification_probabilities', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('classified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='classifier.ClassifiedDocument')),
            ],
            bases=('classifier.basemodel',),
        ),
    ]
