# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classifieddocument_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieddocument',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
