# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classifieddocument_classifiedexcerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieddocument',
            name='group_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
