# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 17:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20171220_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifieddocument',
            old_name='classification',
            new_name='classification_label',
        ),
        migrations.RenameField(
            model_name='classifiedexcerpt',
            old_name='classification',
            new_name='classification_label',
        ),
        migrations.RemoveField(
            model_name='classifieddocument',
            name='details',
        ),
        migrations.AddField(
            model_name='classifieddocument',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='classifieddocument',
            name='classification_probabilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
