# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_classifiermodel_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiermodel',
            old_name='active',
            new_name='is_active',
        ),
    ]
