# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 17:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20171220_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('text', models.TextField()),
                ('classification_label', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('used_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ClassifierModel')),
            ],
            bases=('classifier.basemodel',),
        ),
    ]
