# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='useful',
            field=models.BooleanField(default=False),
        ),
    ]
