# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 07:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_recommendation_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiermodel',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
