version: '3.2'

services:
    db:
        image: postgres:9.6
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        volumes:
            - ./redis-data:/data
        restart: on-failure

    web:
        image: thedeep/deepl:latest
        build:
            context: .
            cache_from:
                - thedeep/deepl:latest
        env_file:
            - .nlp_env_sample
        command: ['/code/deploy/scripts/wait-for-it.sh', 'db:5432', '--', '/code/deploy/scripts/run_develop.sh']
        volumes:
            - .:/code:z
            - ./media:/media:z
            - nlp_data:/nlp_data
        ports:
            - '8010:8000'
        depends_on:
            - db
            - celery
        restart: on-failure

    celery:
        image: thedeep/deepl:latest
        build:
            context: .
            cache_from:
                - thedeep/deepl:latest
        env_file:
            - .nlp_env
        environment:
            - INSTANCE_TYPE=CELERY
        command: ['/code/deploy/scripts/celery.sh']
        volumes:
            - .:/code:z
            - ./media:/media:z
            - nlp_data:/nlp_data
        tty: true
        depends_on:
            - db
            - redis
        restart: on-failure


volumes:
    nlp_data:
