# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiermodel',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='ClassifierModel',
        ),
    ]
