import os

# Variable for storing index files for NLP
INDICES_PATH_ENV_VAR = 'NLP_INDICES_PATH'

TERM_FREQUENCY_INDEX_FILENAME = 'tf_compressed.json'
INVERSE_FREQUENCY_INDEX_FILENAME = 'idf.json'
TERM_INDEX_FILENAME = 'terms_index.json'

# CLUSTERING
ENVIRON_CLUSTERING_DATA_LOCATION = 'DEEPL_CLUSTERING_DATA_LOCATION'

# These files will be stored inside folder 'cluster_model_<id>' corresponding
# to different cluster models
CLUSTERS_CENTERS_FILENAME = 'cluster_centers.data'
CLUSTERED_DOCS_LABELS_FILENAME = 'docs_clusters_labels.data'
RELEVANT_TERMS_FILENAME = 'relevant_terms.data'
CLUSTERS_SCORE_PLOT_FILENAME = 'score_vs_docs_plot.png'
CLUSTER_SCORE_DOCS_SIZE_FILENAME = 'score_vs_size.data'

ENVIRON_CLUSTERS_CENTERS_LOCATION = 'DEEPL_CLUSTERS_CENTER_LOCATION'
ENVIRON_CLUSTERED_DOCS_LABEL_LOCATION = 'DEEPL_CLUSTERED_DOCS_LABEL_LOCATION'


# DOC2VEC
ENVIRON_DOC2VEC_MODELS_LOCATION = 'DOC2VEC_MODELS_LOCATION'


# CLASSIFIER
CLASSIFIER_DATA_PATH = os.environ.get(
    'CLASSIFIER_DATA_PATH',
    '/code/nlp_data/classifier'
)
