
# Variable for storing index files for NLP
INDICES_PATH_ENV_VAR = 'NLP_INDICES_PATH'

TERM_FREQUENCY_INDEX_FILENAME = 'tf.index'
INVERSE_FREQUENCY_INDEX_FILENAME = 'idf.index'
TERM_INDEX_FILENAME = 'terms.index'
