
# Variable for storing index files for NLP
INDICES_PATH_ENV_VAR = 'NLP_INDICES_PATH'

TERM_FREQUENCY_INDEX_FILENAME = 'tf_compressed.json'
INVERSE_FREQUENCY_INDEX_FILENAME = 'idf.json'
TERM_INDEX_FILENAME = 'terms_index.json'

# CLUSTERING
ENVIRON_CLUSTERING_DATA_LOCATION = 'DEEPL_CLUSTERING_DATA_LOCATION'

# These files will be stored inside folder 'cluster_model_<id>' corresponding
# to different cluster models
CLUSTERS_CENTERS_FILENAME = 'cluster_centers.data'
CLUSTERED_DOCS_LABELS_FILENAME = 'docs_clusters_labels.data'

ENVIRON_CLUSTERS_CENTERS_LOCATION = 'DEEPL_CLUSTERS_CENTER_LOCATION'
ENVIRON_CLUSTERED_DOCS_LABEL_LOCATION = 'DEEPL_CLUSTERED_DOCS_LABEL_LOCATION'
