# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0004_clusteringmodel_silhouette_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusteringmodel',
            old_name='version',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='doc2vecmodel',
            old_name='version',
            new_name='group_id',
        ),
    ]
