# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 08:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0005_auto_20180418_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc2vecmodel',
            name='extra_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
