# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0007_clusteringmodel_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringmodel',
            name='last_clustered_on',
            field=models.DateTimeField(null=True),
        ),
    ]
