# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0008_clusteringmodel_last_clustered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringmodel',
            name='last_clustering_started',
            field=models.DateTimeField(null=True),
        ),
    ]
