# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0009_clusteringmodel_last_clustering_started'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusteringmodel',
            unique_together=set([('group_id', 'n_clusters')]),
        ),
    ]
