# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0010_auto_20180606_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringmodel',
            name='group_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
