# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0011_auto_20180611_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringmodel',
            name='all_clustered',
            field=models.BooleanField(default=True),
        ),
    ]
