# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0006_recommendation_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('correlated_entity', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('correlation_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('classifier.basemodel',),
        ),
    ]
