# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20180627_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
