# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 10:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0003_auto_20180501_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModelingModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classifier.BaseModel')),
                ('group_id', models.CharField(max_length=50, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('ready', models.BooleanField(default=False)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            bases=('classifier.basemodel',),
        ),
    ]
