# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0002_auto_20180507_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodelingmodel',
            name='last_run_on',
            field=models.DateField(null=True),
        ),
    ]
