# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0003_topicmodelingmodel_last_run_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodelingmodel',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='topicmodelingmodel',
            unique_together=set([('group_id', 'number_of_topics', 'keywords_per_topic', 'depth')]),
        ),
    ]
