# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20180501_0313'),
        ('NER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NERCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(editable=False)),
                ('modified_on', models.DateTimeField()),
                ('ner_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('classified_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.ClassifiedDocument', unique=True)),
            ],
        ),
    ]
